# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: mypool

variables:
  system.debug: 'true'
  webAppName: nguyenlc1-project2
  projectRoot: $(System.DefaultWorkingDirectory)
  azureServiceConnectionId: 'nguyenlc1-project2'
  environmentName: 'Flask'

stages:
- stage: Build
  displayName: Build Python Flask Web App
  jobs:
  - job: BuildJob
    pool: mypool
    steps:
    - script: |
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install setup
        python3.9 -m pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: 'Upgrade and install python packages'
    
    - script: |
        export PATH=$HOME/.local/bin:$PATH
        make install
      workingDirectory: $(projectRoot)
      displayName: 'Make install'

    - script: |
        export PATH=$HOME/.local/bin:$PATH
        make lint
      workingDirectory: $(projectRoot)
      displayName: 'Run lint tests'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: Deploy Python Flask Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: mypool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
