trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    make install
  displayName: 'Install dependencies'

- script: |
    make lint
  displayName: 'Lint with pylint'

- script: |
    make test
  displayName: 'Test with pytest'
